# Generated by Django 5.2.10 on 2026-06-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_router", "0004_remove_llmlog_retry_count"),
        ("data_room", "0028_doc_json_bilanz_mapped_split_status"),
        ("project", "0069_drop_orphan_ai_document_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[("general", "Allgemein"), ("project", "Projekt"), ("document", "Dokument")],
                        default="general",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Automatisch aus erster Nachricht generiert",
                        max_length=255,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Gerenderter System-Prompt-Snapshot fuer diese Session",
                        verbose_name="System-Prompt",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_chat_sessions",
                        to="data_room.protectedprojectdocument",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_chat_sessions",
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat-Session",
                "verbose_name_plural": "Chat-Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Benutzer"), ("assistant", "AI-Assistent"), ("system", "System")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "retrieved_chunks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="RAG-Chunks mit Score/Seite; Chunk-Text auf 1000 Zeichen truncated — Volltext bleibt im Vector-Store reproduzierbar.",
                    ),
                ),
                (
                    "used_documents",
                    models.JSONField(
                        blank=True, default=list, help_text="Liste der verwendeten Dokument-IDs und Scores"
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(blank=True, help_text="LLM-Provider (z.B. bedrock, azure, vertex)", max_length=50),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "llm_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="ai_router.llmlog",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="ai_chat.chatsession"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat-Nachricht",
                "verbose_name_plural": "Chat-Nachrichten",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RetrievalLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.TextField()),
                ("scope", models.CharField(blank=True, max_length=10)),
                ("project_id", models.IntegerField(blank=True, null=True)),
                ("document_id", models.IntegerField(blank=True, null=True)),
                ("collection", models.CharField(max_length=128)),
                (
                    "candidate_scores",
                    models.JSONField(
                        blank=True, default=list, help_text="Alle fused-RRF-Scores vor dem Cutoff, absteigend"
                    ),
                ),
                ("final_k", models.PositiveIntegerField()),
                (
                    "cutoff_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="rel_floor, elbow_drop, min_k, max_k, backend"
                    ),
                ),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_logs",
                        to="ai_chat.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrieval-Log",
                "verbose_name_plural": "Retrieval-Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user", "is_active"], name="ai_chat_cha_user_id_6be159_idx"),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["user", "-updated_at"], name="ai_chat_cha_user_id_80d8fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "scope", "project", "document"),
                name="unique_active_ai_chat_session_per_scope",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["session", "timestamp"], name="ai_chat_cha_session_4945c3_idx"),
        ),
        migrations.AddIndex(
            model_name="retrievallog",
            index=models.Index(fields=["collection", "created_at"], name="ai_chat_ret_collect_4467a8_idx"),
        ),
    ]
