# Generated by Django 5.2.10 on 2026-06-10 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0001_initial"),
        ("data_room", "0028_doc_json_bilanz_mapped_split_status"),
        ("project", "0069_drop_orphan_ai_document_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatsession",
            name="unique_active_ai_chat_session_per_scope",
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("scope", "general")),
                fields=("user",),
                name="unique_active_general_chat_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("project__isnull", False), ("scope", "project")),
                fields=("user", "project"),
                name="unique_active_project_chat_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False), ("is_active", True), ("scope", "document")),
                fields=("user", "document"),
                name="unique_active_document_chat_session",
            ),
        ),
    ]
